import { Queue, Worker } from 'bullmq';
import bcrypt from 'bcryptjs';
import { getDb, users, userProfiles, otpVerifications } from '@thinkai/db';
import { connection } from './connection';
import { parseCsvBuffer } from '../utils/csv.utils';
import { enqueueEmail } from './email.queue';

const BULK_IMPORT_QUEUE_NAME = 'admin-bulk-import';

// ─── Job types ────────────────────────────────────────────────────────────────

export type BulkImportJobPayload = {
  csvBuffer: number[];  // Array.from(Buffer) for JSON serialization
  defaultRole: string;
  actorId: string;
};

export type BulkImportRowResult = {
  row: number;
  email: string;
  status: 'created' | 'skipped' | 'error';
  reason?: string;
};

export type BulkImportJobResult = {
  total: number;
  created: number;
  skipped: number;
  errors: number;
  rows: BulkImportRowResult[];
};

// ─── Queue ────────────────────────────────────────────────────────────────────

export const bulkImportQueue = new Queue(BULK_IMPORT_QUEUE_NAME, {
  connection,
  defaultJobOptions: {
    attempts: 2,
    backoff: { type: 'exponential', delay: 3000 },
    removeOnComplete: 100,
    removeOnFail: 50
  }
});

export async function enqueueBulkImport(payload: BulkImportJobPayload) {
  return bulkImportQueue.add('bulk:import', payload, {
    jobId: `bulk-import:${payload.actorId}:${Date.now()}`
  });
}

// ─── Worker ───────────────────────────────────────────────────────────────────

export function startBulkImportWorker(logger: { info: (...a: unknown[]) => void; error: (...a: unknown[]) => void }) {
  const BCRYPT_ROUNDS = parseInt(process.env.BCRYPT_ROUNDS ?? '12', 10);

  const worker = new Worker(
    BULK_IMPORT_QUEUE_NAME,
    async (job) => {
      const data = job.data as BulkImportJobPayload;
      const db = getDb();

      const buffer = Buffer.from(data.csvBuffer);
      const rows = await parseCsvBuffer(buffer);

      const results: BulkImportRowResult[] = [];
      let created = 0, skipped = 0, errors = 0;

      for (let i = 0; i < rows.length; i++) {
        const row = rows[i]!;
        const email = (row['email'] ?? '').toLowerCase().trim();
        const password = row['password'] ?? '';

        // ─── Validate ─────────────────────────────────────────────────────
        if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
          results.push({ row: i + 1, email, status: 'error', reason: 'Invalid email' });
          errors++;
          continue;
        }
        let finalPassword = password;
        let isAutoGenerated = false;
        if (!finalPassword) {
          // If password left blank, generate a random secure one
          // User will need to set password via reset link
          finalPassword = require('node:crypto').randomBytes(16).toString('hex');
          isAutoGenerated = true;
        } else if (finalPassword.length < 8) {
          results.push({ row: i + 1, email, status: 'error', reason: 'Password must be ≥8 chars' });
          errors++;
          continue;
        }

        // ─── Uniqueness check ─────────────────────────────────────────────
        const existing = await db
          .select({ id: users.id })
          .from(users)
          .where(require('drizzle-orm').eq(users.email, email))
          .limit(1);

        if (existing.length > 0) {
          results.push({ row: i + 1, email, status: 'skipped', reason: 'Email already exists' });
          skipped++;
          continue;
        }

        // ─── Create ───────────────────────────────────────────────────────
        try {
          const passwordHash = await bcrypt.hash(finalPassword, BCRYPT_ROUNDS);
          const roleVal = (row['role'] ?? data.defaultRole ?? 'free') as typeof users.$inferInsert['role'];

          const [user] = await db.insert(users).values({
            email,
            passwordHash,
            role: roleVal,
            status: 'active',
            emailVerified: true,
            authProvider: 'local'
          }).returning();

          const fullName = (row['fullName'] ?? row['full_name'] ?? email.split('@')[0]!).trim();
          await db.insert(userProfiles).values({
            userId: user!.id,
            fullName,
            preferences: {}
          });

          if (isAutoGenerated) {
            const otpCode = Math.floor(100000 + Math.random() * 900000).toString();
            const otpHash = require('node:crypto').createHash('sha256').update(otpCode).digest('hex');

            await db.insert(otpVerifications).values({
              userId: user!.id,
              email: email,
              otpCode: otpHash,
              type: 'RESET_PASSWORD',
              expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000) // 24 hours
            });

            await enqueueEmail({
              to: email,
              templateName: 'password_reset',
              variables: {
                email,
                name: fullName,
                otp: otpCode,
                appUrl: process.env.APP_URL || 'http://localhost:3000'
              }
            });
          }

          results.push({ row: i + 1, email, status: 'created' });
          created++;
        } catch (err: any) {
          results.push({ row: i + 1, email, status: 'error', reason: err?.message ?? 'DB error' });
          errors++;
        }

        // Report progress every 50 rows
        if ((i + 1) % 50 === 0) {
          await job.updateProgress(Math.round(((i + 1) / rows.length) * 100));
        }
      }

      const summary: BulkImportJobResult = {
        total: rows.length,
        created,
        skipped,
        errors,
        rows: results
      };

      logger.info({ actorId: data.actorId, ...summary }, 'Bulk import complete');
      return summary;
    },
    { connection, concurrency: 1 }
  );

  worker.on('error', (err) => logger.error({ err }, 'Bulk import worker error'));
  return worker;
}
